export const  REGISTER_SET_EXAMS = 'REGISTER_SET_EXAMS';

export const  EXAM_TITLE = 'EXAM_TITLE';

export const  CREATE_EXAM_BEGIN = 'CREATE_USER_BEGIN';
export const  CREATE_EXAM_SUCESS = 'CREATE_EXAM_SUCESS';
export const  CREATE_EXAM_ERROR = 'CREATE_EXAM_ERROR';

export const CLEAR_TITLE_QUESTION = 'CLEAR_TITLE_QUESTION';


export const GET_EXAM_LIST = 'GET_EXAM_LIST';